# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12waavXsWvOZPXKgzX1lAWSOXsZzZm7kf
"""

class Triangle:
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def is_valid(self):
        return (self.a + self.b > self.c) and (self.a + self.c > self.b) and(self.b + self.c > self.a)

    def perimeter(self):
        return self.a + self.b + self.c

    def area(self):
        if not self.is_valid():
            return None
        s = self.perimeter() / 2.0
        return (s * (s - self.a)*(s - self.b)*(s - self.c))**0.5

triangle = Triangle (3, 4, 5)
print(triangle.is_valid())
print(triangle.perimeter())
print(triangle.area())

class Cube:
    def __init__(self, side):
        self.side = side

    def surface_area(self):
        return 6 * (self.side ** 2)

    def volume(self):
        return self.side ** 3

    def diagonal(self):
        return (3* self.side ** 2) ** 0.5

cube = Cube(4)
print(cube.surface_area())
print(cube.volume())
print(cube.diagonal())